name: CI for Notes Manager

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.3'

    - name: Validate code structure
      run: |
        echo "Проверка структуры проекта"
        ls -la auth-service/
        ls -la notes-service/ 
        ls -la frontend-service/
        echo "Структура проекта корректна"

    - name: Build Docker images
      run: |
        docker build -t auth-service:ci ./auth-service
        docker build -t notes-service:ci ./notes-service
        docker build -t frontend:ci ./frontend-service

    - name: Verify images
      run: |
        echo "Все образы успешно собраны :"
        docker images | grep -E "(auth-service|notes-service|frontend)"